<div class="checkout-page">
    <header class="page-heading"><p class="eyebrow">Secure checkout</p><h1>Delivery details</h1><p>All fields are required unless marked optional.</p></header>
    <form wire:submit="placeOrder" class="checkout-layout" novalidate>
        <div class="checkout-form">
            @if($errors->has('cart'))<div class="form-alert" role="alert">{{ $errors->first('cart') }}</div>@endif
            <fieldset><legend>Contact</legend><div class="form-grid two-columns"><x-form-field name="customer_name" label="Full name" autocomplete="name" /><x-form-field name="customer_email" label="Email address" type="email" autocomplete="email" /><x-form-field name="customer_phone" label="Mobile number" type="tel" autocomplete="tel" inputmode="tel" /></div></fieldset>
            <fieldset><legend>Shipping address</legend><div class="form-grid two-columns"><x-form-field name="shipping_address" label="Street address" autocomplete="street-address" class="full-span" /><x-form-field name="shipping_city" label="City / municipality" autocomplete="address-level2" /><x-form-field name="shipping_province" label="Province" autocomplete="address-level1" /><x-form-field name="shipping_postal_code" label="Postal code" autocomplete="postal-code" inputmode="numeric" /></div></fieldset>
            <fieldset><legend>Payment</legend><label class="payment-option"><input type="radio" wire:model="payment_method" value="cod"><span><strong>Cash on delivery</strong><small>Pay securely when your order arrives.</small></span></label></fieldset>
            <label class="field full-span"><span>Order notes <small>(optional)</small></span><textarea wire:model="customer_notes" rows="3" placeholder="Delivery instructions or other notes"></textarea>@error('customer_notes')<small class="field-error" role="alert">{{ $message }}</small>@enderror</label>
        </div>
        <aside class="order-summary checkout-summary"><h2>Your order</h2>@foreach($items as $item)<div class="checkout-item"><img src="{{ $item['variant']->product->primary_image_url }}" width="72" height="72" alt=""><span><strong>{{ $item['variant']->product->name }}</strong><small>Size {{ $item['variant']->size }} · Qty {{ $item['quantity'] }}</small></span><span>₱{{ number_format($item['line_total'] / 100, 2) }}</span></div>@endforeach<dl><div><dt>Subtotal</dt><dd>₱{{ number_format($subtotal / 100, 2) }}</dd></div><div><dt>Shipping</dt><dd>{{ $shipping ? '₱'.number_format($shipping / 100, 2) : 'Free' }}</dd></div><div class="summary-total"><dt>Total</dt><dd>₱{{ number_format($total / 100, 2) }}</dd></div></dl><button class="primary-button" type="submit" wire:loading.attr="disabled"><span wire:loading.remove wire:target="placeOrder">Place order</span><span wire:loading wire:target="placeOrder">Placing order…</span></button><p>By ordering, you agree to our authenticity, delivery, and returns policies.</p></aside>
    </form>
</div>
